name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_03f561d6968eb4b5335ec8de677b21a8b671a595
      SUPABASE_DB_PASSWORD: rasim=dHTmues1nXViuIVB
      SUPABASE_PROJECT_ID: rkyfikgaznqjywzoskpj

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
